# server 配置
server:
  port: 8089
  servlet:
    context-path: /demo02
# spring 数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ych?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Cyw050130
# mybatis 配置
mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true